# Generated by Django 5.0.6 on 2024-06-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messeng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_edit_message', 'Can edit message'), ('can_remove_message', 'Can remove message')]},
        ),
    ]
